package org.gris.core.engine;

import org.gris.core.metrics.AggregatedMetric;

import java.util.List;
import java.util.Map;

/**
 * Report generated by the ReplicationRunner after executing N Monte Carlo replications.
 * Contains aggregated sample metrics, time-weighted averages, and counters with 95% confidence intervals.
 */
public record ReplicationReport(
        String modelName,
        int replications,
        double horizon,
        long baseSeed,
        long totalEventsProcessed,
        long wallClockMillis,
        Map<String, AggregatedMetric> sampleMetrics,
        Map<String, AggregatedMetric> timeWeightedMetrics,
        Map<String, AggregatedMetric> counters,
        List<SimulationResult> individualRuns
) {

    public AggregatedMetric getSampleMetric(String name) {
        AggregatedMetric metric = sampleMetrics.get(name);
        if (metric == null) {
            throw new IllegalArgumentException("Sample metric not found in report: " + name);
        }
        return metric;
    }

    public AggregatedMetric getTimeWeightedMetric(String name) {
        AggregatedMetric metric = timeWeightedMetrics.get(name);
        if (metric == null) {
            throw new IllegalArgumentException("Time-weighted metric not found in report: " + name);
        }
        return metric;
    }

    public AggregatedMetric getCounter(String name) {
        AggregatedMetric metric = counters.get(name);
        if (metric == null) {
            throw new IllegalArgumentException("Counter not found in report: " + name);
        }
        return metric;
    }
}
